language: android
sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

jdk:
    - oraclejdk8

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"

install:
    - sdkmanager --list || true
    - echo yes | sdkmanager "tools"
    - echo yes | sdkmanager "platforms;android-28"
    - echo yes | sdkmanager "extras;google;m2repository"
    - echo yes | sdkmanager "extras;android;m2repository"
    - sdkmanager --list || true

script:
    - ./gradlew clean && ./gradlew assembleRelease && ./gradlew copyForRelease
    - ./gradlew clean && ./gradlew assembleDebug && ./gradlew copyForDebug

notifications:
    email:
        - tech@hikyson.cn

deploy:
    - provider: releases
      api_key: $GITHUB_TOKEN
      file:
        - "./github_release/app-release.apk"
        - "./github_release/app-debug.apk"
      skip_cleanup: true
      on:
        tags: true
        branch: master

after_success:
    - echo I am done, release url:https://github.com/Kyson/AndroidGodEyeDemo/releases.